{% set name = "seqan-library" %}
{% set version = "2.5.0" %}
{% set sha256 = "03a605e44d60e0a04b5822db4abd590f252012b2c579fd1167a09daeba758fce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://github.com/seqan/seqan/releases/download/seqan-v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<33 and win]
  script: cp -r include share $PREFIX  # [unix]

test:
  commands:
    - test -f $PREFIX/include/seqan/seq_io.h  # [unix]
    - test -f $PREFIX/share/cmake/seqan/seqan-config.cmake  # [unix]
    - if not exist "%PREFIX%"\\include\\seqan\\seq_io.h exit 1  # [win]
    - if not exist "%PREFIX%"\\share\\cmake\\seqan\\seqan-config.cmake exit 1  # [win]

about:
  home: https://www.seqan.de
  license: BSD-3-Clause
  license_file: share/doc/seqan/LICENSE
  summary: 'SeqAn is a C++ library for the analysis of biological sequence data.'
  description: |
    SeqAn contains a header only library and some associated tools.
    This package does *not* contain those tools, but only the library
    (the files in `include` and `share`).
  dev_url: https://github.com/seqan/seqan

extra:
  recipe-maintainers:
    - aseyboldt
