travis:
  secure:
    BINSTAR_TOKEN: L/8wbqNXx+oNIVKz6Git2MzRwH9IO9phDefiFp3kVC/5pVv42G046c02OpRmqmXm9L/Qv5Rvx6DlJvb+M3SJvXH9tQ6A8d3gCE0zHn24LvjN0d2Vxf4G1SK9FCOGCRTXksJw+joCf+eYw73vX+/ExS5IsNTiw8zJsnV3yqv9QQ+03y1YSGWa7DExQx5GB8sMUpNnGs1ouRa5kFdexygsKVavcEyxkU8UmVS6SZfBCxh7pPuaXFkcZFmfuD8oES1EQ1Cv51AODScPpwDCt29iFydhpxFZ2ATxySZyWqCY4T34CVWEV8+xvES2kgW9n62GA8wbrDSpC0GYFASncNH9RISWCBQlXBh3cSCf+3yy4A2hRCcYudItYjma3Sj18YkHnr0kOce8L0VTHpvCLkkXi53Xq/ZeMK05OKNdYLZtWeZJfdwV7JqZ0hike01sRBXR7DxlEfUXViRQzpIAdzOLu/IMEXrtYPHeHz4PmV1tVzga1qQltaBM66K++pC7uGNg14EU7/TpUOkCcT2EV8jKOynuTjiCZZH9IZ6BdXmu0w3APDpMduGdg0zWWSdMGSHeEwY4NI/9jvUb9qGqohFYMvtv/Baw3IfwSNOg5/DA+TMaZdm/ANb64WE2zc/WYg/EhBrD1kjtdb7/nfz4ObotcuVaGJ5+X8Dna+lnqDHse48=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
