travis:
  secure:
    BINSTAR_TOKEN: AQJeHVnHy7wlgXocKksZMhgaI4Bcekdq92g1BUzcgR9d8ZYBBaAz8JYp+4elL9vUmsZNuzZ2wMXS7KSG/RJ9xW5wRlwVSbd0TWNe+Sivgbl3/FiyEgKA9fvuhun5ltRKssVPmZ/PTwzh1wC4Rtxrk7G1O3R6bneAZDU0FG1igO9LNDTVzhRD+BdSsunvyoolsHBizzwzKa7sc5WctgFwyHsSM3VvmH495PFB+Y9j7fwm4rWOYtLD2X9oHTZFTB0cUfaUfYDOsz/cMy5p9zkorz+OP2DnrSFROGJ5SP7at5xGM/vEz6B9PGIzyQ+DfkrMhz8rhGqTDhZUK4Kz/0JDNF9INSdRABDS7UjxxzNUBotQVe6b27lAU2iUt93i+PCl7EwYw65GanJmK84BQffYiFfl2mZZWaaLRFmse45unvkuL6YJ4MZLXw62orqBTzll9go0J/QACfaR2j5VjvfciztTSkVA7eJp1G2YlKWxNclK//vArIJULYiyV3EZeeZUun2JEPkkgGGRsAMNbbJo8QcLBr3zldCMiqDepS/vfozkKQrbjAeQQ6fzYS31x76i5dr0b5mIbbaRwuOLRiO1d/8G1PjIuW5eBE62W3oZvZWsRfO3NNBuJWD1dz8g+/EOa+1W6zgIfdyf3mxcDCuqrUt8PX+UXwMt7ILehUSAYcw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
